### ISSUE TITLE
IMPORTANT - Most of the html has been commented out.

### ISSUE THREAD

**Issue by Emik234** [beccap7/prj-rev-bwfs-tea-cozy#1]
Not sure what's going on but the rest of your HTML has been commented out. 

https://github.com/beccap7/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L9-L126

**Comment by beccap7** [comment]
That was supposed to be comments to group the different sections to help keep track of where I was. I'm not sure if I did it right
