### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by Emik234** [beccap7/prj-rev-bwfs-tea-cozy#4]
Project name: TeaCozy
Summary Grade: Satisfactory

Great job on the visual design of the site! It matched closely to the original site! Your use of multi-line comments and indentation was a breath of fresh air and very good habit to keep up with

The area of improvement I would say is to take a look at the issue of most of your Html being commented out.

As a further challenge, consider adding a few videos that can be auto played, muted and looped. This will take some extra research but could be a really valuable way to challenge yourself to push past what you’ve already learned. Based on your work here, I think it’s a challenge you’re ready for.

**Comment by beccap7** [comment]
Thanks for your review! The only issue I had on my end was making the mission statement stay on the background; it kept "hiding" behind the header/nav bar. Also, sorry if the comments were confusing; don't know why some of the code was removed.
